sonar.projectKey=ferxarp-frontend
sonar.projectName=FERXARP Frontend
sonar.projectVersion=0.1.0
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx
sonar.exclusions=src/**/*.test.ts,src/**/*.test.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
