//! Fictional fixtures only. Coordinates are approximate, not real addresses.
pub struct NgoSeed {
    pub email: &'static str,
    pub name: &'static str,
    pub needs: &'static str,
    pub lat: f64,
    pub lon: f64,
}

pub const COMPANIES: [&str; 6] = [
    "alimentos-veracruz@demo.ferxarp.invalid",
    "tecnologia-boca@demo.ferxarp.invalid",
    "mobiliario-centro@demo.ferxarp.invalid",
    "suministros-medellin@demo.ferxarp.invalid",
    "herramientas-puerto@demo.ferxarp.invalid",
    "textiles-veracruz@demo.ferxarp.invalid",
];

pub const NGOS: [NgoSeed; 10] = [
    NgoSeed {
        email: "banco-veracruz@demo.ferxarp.invalid",
        name: "Banco Comunitario Demo Veracruz",
        needs: "Alimentos, leche, arroz, frijol y productos de limpieza para comedores.",
        lat: 19.1834,
        lon: -96.1550,
    },
    NgoSeed {
        email: "educacion-boca@demo.ferxarp.invalid",
        name: "Fundación Educativa Demo Boca",
        needs: "Material escolar, laptops, monitores, escritorios, sillas y uniformes.",
        lat: 19.1120,
        lon: -96.1080,
    },
    NgoSeed {
        email: "comedor-centro@demo.ferxarp.invalid",
        name: "Comedor Social Demo Centro",
        needs: "Alimentos, leche, arroz, frijol, limpieza y herramientas de cocina.",
        lat: 19.1982,
        lon: -96.1384,
    },
    NgoSeed {
        email: "refugio-medellin@demo.ferxarp.invalid",
        name: "Refugio Comunitario Demo Medellín",
        needs: "Alimentos, leche, uniformes, sillas y productos de limpieza.",
        lat: 19.0660,
        lon: -96.1570,
    },
    NgoSeed {
        email: "ambiente-puerto@demo.ferxarp.invalid",
        name: "Asociación Ambiental Demo Puerto",
        needs: "Herramientas, tarimas, uniformes y material escolar para talleres.",
        lat: 19.2160,
        lon: -96.1620,
    },
    NgoSeed {
        email: "aula-veracruz@demo.ferxarp.invalid",
        name: "Aula Digital Demo Veracruz",
        needs: "Laptops, computadoras, monitores, escritorios y material escolar.",
        lat: 19.1712,
        lon: -96.1310,
    },
    NgoSeed {
        email: "red-boca@demo.ferxarp.invalid",
        name: "Red Solidaria Demo Boca",
        needs: "Leche, alimentos, limpieza, material escolar y uniformes.",
        lat: 19.1420,
        lon: -96.1180,
    },
    NgoSeed {
        email: "taller-medellin@demo.ferxarp.invalid",
        name: "Taller Comunitario Demo Medellín",
        needs: "Herramientas, tarimas, escritorios, sillas y monitores.",
        lat: 19.0800,
        lon: -96.1710,
    },
    NgoSeed {
        email: "centro-puerto@demo.ferxarp.invalid",
        name: "Centro Vecinal Demo Puerto",
        needs: "Alimentos, leche, limpieza y sillas para actividades comunitarias.",
        lat: 19.2050,
        lon: -96.1520,
    },
    NgoSeed {
        email: "comunidad-centro@demo.ferxarp.invalid",
        name: "Comunidad Demo Centro · pendiente",
        needs: "Material escolar, alimentos y limpieza. Perfil demo pendiente de verificación.",
        lat: 19.1905,
        lon: -96.1265,
    },
];

pub struct DonationSeed {
    pub title: &'static str,
    pub description: &'static str,
    pub quantity: i32,
    pub company: usize,
    pub ngo: usize,
    pub status: &'static str,
    pub approved: bool,
}

pub const DONATIONS: [DonationSeed; 20] = [
    DonationSeed {
        title: "Demo · Leche sellada",
        description: "Leche para comedores; cantidad expresada en cajas.",
        quantity: 80,
        company: 0,
        ngo: 0,
        status: "en_acopio",
        approved: false,
    },
    DonationSeed {
        title: "Demo · Arroz y frijol",
        description: "Alimentos en paquetes cerrados.",
        quantity: 120,
        company: 0,
        ngo: 2,
        status: "en_acopio",
        approved: false,
    },
    DonationSeed {
        title: "Demo · Laptops educativas",
        description: "Laptops de demostración para aulas.",
        quantity: 12,
        company: 1,
        ngo: 1,
        status: "en_acopio",
        approved: false,
    },
    DonationSeed {
        title: "Demo · Monitores",
        description: "Monitores para equipamiento educativo.",
        quantity: 15,
        company: 1,
        ngo: 5,
        status: "en_acopio",
        approved: false,
    },
    DonationSeed {
        title: "Demo · Escritorios",
        description: "Escritorios para aulas y talleres.",
        quantity: 10,
        company: 2,
        ngo: 7,
        status: "en_acopio",
        approved: false,
    },
    DonationSeed {
        title: "Demo · Kits de limpieza",
        description: "Productos de limpieza en kits cerrados.",
        quantity: 40,
        company: 3,
        ngo: 3,
        status: "en_acopio",
        approved: false,
    },
    DonationSeed {
        title: "Demo · Herramientas de taller",
        description: "Juegos de herramientas manuales.",
        quantity: 18,
        company: 4,
        ngo: 4,
        status: "en_acopio",
        approved: false,
    },
    DonationSeed {
        title: "Demo · Uniformes",
        description: "Uniformes para actividades comunitarias.",
        quantity: 60,
        company: 5,
        ngo: 6,
        status: "en_acopio",
        approved: false,
    },
    DonationSeed {
        title: "Demo · Despensas solicitadas",
        description: "Alimentos solicitados, todavía sin aprobación.",
        quantity: 35,
        company: 0,
        ngo: 0,
        status: "reservado",
        approved: false,
    },
    DonationSeed {
        title: "Demo · Material escolar solicitado",
        description: "Paquetes de cuadernos y lápices, sin aprobación.",
        quantity: 50,
        company: 3,
        ngo: 1,
        status: "reservado",
        approved: false,
    },
    DonationSeed {
        title: "Demo · Leche aprobada",
        description: "Cajas de leche aprobadas; la salida física sigue pendiente.",
        quantity: 25,
        company: 0,
        ngo: 0,
        status: "reservado",
        approved: true,
    },
    DonationSeed {
        title: "Demo · Sillas aprobadas",
        description: "Sillas aprobadas; todavía sin salida física.",
        quantity: 30,
        company: 2,
        ngo: 7,
        status: "reservado",
        approved: true,
    },
    DonationSeed {
        title: "Demo · Alimentos en tránsito",
        description: "Lote de alimentos para demostrar recepción.",
        quantity: 45,
        company: 0,
        ngo: 0,
        status: "en_transito",
        approved: true,
    },
    DonationSeed {
        title: "Demo · Leche para revisión",
        description: "Segundo lote independiente para demostrar rechazo con motivo.",
        quantity: 20,
        company: 0,
        ngo: 0,
        status: "en_transito",
        approved: true,
    },
    DonationSeed {
        title: "Demo · Laptops en tránsito",
        description: "Laptops con salida registrada hacia un aula.",
        quantity: 8,
        company: 1,
        ngo: 5,
        status: "en_transito",
        approved: true,
    },
    DonationSeed {
        title: "Demo · Tarimas en tránsito",
        description: "Tarimas para actividades de taller.",
        quantity: 22,
        company: 4,
        ngo: 4,
        status: "en_transito",
        approved: true,
    },
    DonationSeed {
        title: "Demo · Despensas recibidas",
        description: "Ejemplo simulado de alimentos recibidos.",
        quantity: 60,
        company: 0,
        ngo: 0,
        status: "entregado",
        approved: true,
    },
    DonationSeed {
        title: "Demo · Uniformes recibidos",
        description: "Ejemplo simulado de uniformes recibidos.",
        quantity: 35,
        company: 5,
        ngo: 6,
        status: "entregado",
        approved: true,
    },
    DonationSeed {
        title: "Demo · Limpieza rechazada",
        description: "Ejemplo simulado de rechazo por embalaje dañado.",
        quantity: 10,
        company: 0,
        ngo: 0,
        status: "rechazado",
        approved: true,
    },
    DonationSeed {
        title: "Demo · Escritorios rechazados",
        description: "Ejemplo simulado de rechazo por piezas faltantes.",
        quantity: 6,
        company: 2,
        ngo: 7,
        status: "rechazado",
        approved: true,
    },
];
